name: Update Proton Version in README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # No need to pass token here, it is automatically handled by GitHub Actions
      
      - name: Set Proton Version
        run: |
          proton_version="GE-Proton9-12"
          user_name="Nightro-Fx"
          sed -i "s|wineroot = \"/home/ur_username/.local/share/Steam/compatibilitytools.d/GE-Proton[^\"]*\"|wineroot = \"/home/$user_name/.local/share/Steam/compatibilitytools.d/$proton_version\"|g" README.md
          sed -i "s|PROTONPATH = \"/home/ur_username/.local/share/Steam/compatibilitytools.d/GE-Proton[^\"]*\"|PROTONPATH = \"/home/$user_name/.local/share/Steam/compatibilitytools.d/$proton_version\"|g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update Proton version in README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # This is passed for pushing changes
